version: '3.8'

services:
  researchmate:
    build: .
    container_name: researchmate-app
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./chroma_persist:/app/chroma_persist
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - researchmate-network

networks:
  researchmate-network:
    driver: bridge

volumes:
  data:
  logs:
  uploads:
  chroma_persist:
